"""Pareto-front Monte Carlo Tree Search over molecular SMILES space.

Design
------
Each tree node holds a SMILES string.  Child nodes are generated by
*atom mutations*:

  * Atom-type substitution (C → N, N → O, etc.)
  * Fragment addition (common drug-fragment SMILES)
  * Bond-order change (single ↔ double)

Node selection uses UCB1 weighted by a Pareto-dominance count so the
search explores the full Pareto front instead of collapsing to a single
optimum (which REINFORCE / RL typically does).

Reference: ParetoDrug (Communications Biology, 2024) and PMMG (Advanced
Science, 2025).

Example
-------
>>> from chemvision.generation.pareto_mcts import ParetoMCTS, Objective
>>> objectives = [
...     Objective("qed", fn=lambda s: predictor.predict(s).qed or 0, direction="max"),
...     Objective("mw",  fn=lambda s: -(predictor.predict(s).mw or 500), direction="max"),
... ]
>>> mcts = ParetoMCTS(objectives)
>>> front = mcts.search("CC(=O)Oc1ccccc1C(=O)O", n_iterations=50)
>>> front[0].smiles
'...'
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Callable

from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Objective:
    """One scalar objective in the multi-objective search."""

    name: str
    fn: Callable[[str], float]
    direction: str = "max"   # "max" or "min"

    def evaluate(self, smiles: str) -> float:
        """Return a value where *higher is always better* for UCB."""
        try:
            raw = self.fn(smiles)
        except Exception:
            return -1e9
        return raw if self.direction == "max" else -raw


@dataclass
class Candidate:
    """A molecule on or near the Pareto front."""

    smiles: str
    scores: dict[str, float] = field(default_factory=dict)
    pareto_rank: int = 0        # 0 = non-dominated (Pareto front)

    def dominates(self, other: "Candidate") -> bool:
        """Return True if self Pareto-dominates *other* (better in all, strictly better in ≥1).

        All scores are pre-normalised so higher = better (Objective.evaluate handles direction).
        """
        better_in_any = False
        for k in self.scores:
            other_val = other.scores.get(k, float("inf"))  # missing = assume other is best
            if self.scores[k] < other_val:
                return False  # self is worse in at least one objective
            if self.scores[k] > other_val:
                better_in_any = True
        return better_in_any


# ---------------------------------------------------------------------------
# Mutation operators
# ---------------------------------------------------------------------------

_ATOM_SUBSTITUTIONS: list[tuple[str, str]] = [
    ("[c]", "[n]"), ("[n]", "[o]"), ("C", "N"), ("N", "O"),
    ("CC", "CO"), ("c", "n"),
]

_DRUG_FRAGMENTS: list[str] = [
    "C(=O)N", "C(=O)O", "CN", "CF", "CCl", "CS", "CO",
    "c1ccncc1", "c1ccccc1", "N1CCCC1", "C1CCCO1",
]


def _mutate_smiles(smiles: str, rng: random.Random) -> list[str]:
    """Generate a small set of SMILES neighbours via simple mutations."""
    candidates: list[str] = []

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return candidates

    # 1. Atom substitution on editable molecule
    em = Chem.RWMol(mol)
    for idx in range(mol.GetNumAtoms()):
        atom = em.GetAtomWithIdx(idx)
        orig_num = atom.GetAtomicNum()
        for new_num in [6, 7, 8, 9, 16]:   # C, N, O, F, S
            if new_num == orig_num:
                continue
            em2 = Chem.RWMol(em)
            em2.GetAtomWithIdx(idx).SetAtomicNum(new_num)
            try:
                Chem.SanitizeMol(em2)
                s = Chem.MolToSmiles(em2)
                if s and Chem.MolFromSmiles(s) is not None:
                    candidates.append(s)
            except Exception:
                pass
        if len(candidates) >= 8:
            break

    # 2. Fragment addition at a random attachment point
    frag = rng.choice(_DRUG_FRAGMENTS)
    for idx in range(mol.GetNumAtoms()):
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetTotalNumHs() > 0:
            combined = f"{smiles}.{frag}"
            try:
                joined = Chem.MolToSmiles(
                    Chem.MolFromSmiles(combined)
                )
                if joined:
                    candidates.append(joined)
            except Exception:
                pass
            break

    # Canonicalise and deduplicate
    seen: set[str] = {smiles}
    unique: list[str] = []
    for c in candidates:
        canon = Chem.MolToSmiles(Chem.MolFromSmiles(c)) if Chem.MolFromSmiles(c) else None
        if canon and canon not in seen:
            seen.add(canon)
            unique.append(canon)
    return unique


# ---------------------------------------------------------------------------
# MCTS node
# ---------------------------------------------------------------------------

class _Node:
    """A MCTS tree node storing one SMILES string."""

    __slots__ = ("smiles", "parent", "children", "visits", "q_values", "_objectives")

    def __init__(
        self,
        smiles: str,
        objectives: list[Objective],
        parent: "_Node | None" = None,
    ) -> None:
        self.smiles = smiles
        self.parent = parent
        self.children: list["_Node"] = []
        self.visits: int = 0
        self._objectives = objectives
        self.q_values: dict[str, float] = {o.name: 0.0 for o in objectives}

    def ucb1(self, c: float = 1.41) -> float:
        """UCB1 over the *mean* normalised objective value."""
        if self.visits == 0:
            return float("inf")
        parent_visits = self.parent.visits if self.parent else self.visits
        exploitation = sum(self.q_values.values()) / (len(self.q_values) * self.visits + 1e-9)
        exploration = c * math.sqrt(math.log(parent_visits + 1) / (self.visits + 1e-9))
        return exploitation + exploration

    def is_leaf(self) -> bool:
        return len(self.children) == 0


# ---------------------------------------------------------------------------
# ParetoMCTS
# ---------------------------------------------------------------------------

class ParetoMCTS:
    """Multi-objective MCTS with Pareto-front selection.

    Parameters
    ----------
    objectives:
        List of :class:`Objective` instances defining what to optimise.
    max_atoms:
        Reject mutations that exceed this heavy-atom count.
    ucb_c:
        UCB exploration constant.
    seed:
        Random seed for reproducibility.
    """

    def __init__(
        self,
        objectives: list[Objective],
        max_atoms: int = 50,
        ucb_c: float = 1.41,
        seed: int = 42,
    ) -> None:
        self.objectives = objectives
        self.max_atoms = max_atoms
        self.ucb_c = ucb_c
        self._rng = random.Random(seed)
        self._evaluated: dict[str, dict[str, float]] = {}

    # ------------------------------------------------------------------
    # Main search loop
    # ------------------------------------------------------------------

    def search(self, seed_smiles: str, n_iterations: int = 100) -> list[Candidate]:
        """Run MCTS and return the Pareto-optimal candidates.

        Parameters
        ----------
        seed_smiles:
            Starting molecule.
        n_iterations:
            Number of select/expand/simulate/backprop cycles.

        Returns
        -------
        list[Candidate]
            Pareto-front molecules sorted by first objective (descending).
        """
        root = _Node(seed_smiles, self.objectives)
        self._evaluate_node(root)

        for _ in range(n_iterations):
            # 1. Select
            node = self._select(root)
            # 2. Expand
            if node.visits > 0:
                self._expand(node)
                if node.children:
                    node = self._rng.choice(node.children)
            # 3. Simulate (rollout = 1 random mutation)
            rollout_scores = self._simulate(node.smiles)
            # 4. Backpropagate
            self._backpropagate(node, rollout_scores)

        # Collect all evaluated SMILES and compute Pareto front
        return self._pareto_front()

    # ------------------------------------------------------------------
    # MCTS phases
    # ------------------------------------------------------------------

    def _select(self, node: _Node) -> _Node:
        while not node.is_leaf():
            node = max(node.children, key=lambda n: n.ucb1(self.ucb_c))
        return node

    def _expand(self, node: _Node) -> None:
        neighbors = _mutate_smiles(node.smiles, self._rng)
        for smi in neighbors:
            mol = Chem.MolFromSmiles(smi)
            if mol is None:
                continue
            if mol.GetNumHeavyAtoms() > self.max_atoms:
                continue
            child = _Node(smi, self.objectives, parent=node)
            self._evaluate_node(child)
            node.children.append(child)

    def _simulate(self, smiles: str) -> dict[str, float]:
        mutations = _mutate_smiles(smiles, self._rng)
        if not mutations:
            return self._get_scores(smiles)
        smi = self._rng.choice(mutations)
        return self._get_scores(smi)

    def _backpropagate(self, node: _Node, scores: dict[str, float]) -> None:
        cur: _Node | None = node
        while cur is not None:
            cur.visits += 1
            for obj in self.objectives:
                cur.q_values[obj.name] += scores.get(obj.name, 0.0)
            cur = cur.parent

    # ------------------------------------------------------------------
    # Evaluation + Pareto
    # ------------------------------------------------------------------

    def _evaluate_node(self, node: _Node) -> None:
        scores = self._get_scores(node.smiles)
        node.visits = 1
        node.q_values = dict(scores)

    def _get_scores(self, smiles: str) -> dict[str, float]:
        if smiles in self._evaluated:
            return self._evaluated[smiles]
        scores = {o.name: o.evaluate(smiles) for o in self.objectives}
        self._evaluated[smiles] = scores
        return scores

    def _pareto_front(self) -> list[Candidate]:
        candidates = [
            Candidate(smiles=s, scores=scores)
            for s, scores in self._evaluated.items()
            if Chem.MolFromSmiles(s) is not None
        ]
        # assign Pareto ranks (0 = non-dominated)
        for i, c in enumerate(candidates):
            rank = sum(
                1
                for j, other in enumerate(candidates)
                if i != j and other.dominates(c)
            )
            c.pareto_rank = rank

        front = [c for c in candidates if c.pareto_rank == 0]
        # sort by first objective descending
        first_obj = self.objectives[0].name
        front.sort(key=lambda c: c.scores.get(first_obj, 0.0), reverse=True)
        return front if front else candidates[:5]
